language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.3'

install:
    - composer install --ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
